# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802db3670681aa8991d716137fa9fc09c111506f251b7df3d430af764cbcff78ce5d9b13be18095584c7c28495e613ec4c3a968b8a29a238fd08855e279936c4

test:
  secret_key_base: 55dd8fab31972fb0b958b24d6a46ceadc3597ce89f51457abdd9873a58150cc016262a341008e31997e5b7580e2bc9f67c404a455a3f8cf1a40b06fb55c3fe9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
